name: Sync LeetCode Solutions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Automatically stops if stuck longer than 10 minutes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync LeetCode
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions
          verbose: true
